import { Logger } from '@nestjs/common';
import * as fs from 'fs-extra';
import * as path from 'path';

/**
 * Writes the etienne hook-bridge plugin into `<projectRoot>/.opencode/plugin/`
 * so the embedded OpenCode server reports tool executions back to the backend
 * (PreToolUse/PostToolUse parity with the Claude Agent SDK path).
 *
 * OpenCode loads `{plugin,plugins}/*.{ts,js}` from its config directories —
 * we write to `plugin/` only (writing both would double-load). The plugin runs
 * inside the OpenCode server process (Bun), where `fetch` is available.
 *
 * The file embeds a per-boot shared secret; content is compared before writing
 * so an unchanged plugin isn't rewritten (OpenCode instances live per backend
 * boot, and the token changes with each boot, so the first run after a restart
 * rewrites it exactly once per project).
 */
export async function provisionHookPlugin(opts: {
  logger: Logger;
  projectRoot: string;
  projectDir: string;
  token: string;
  backendPort?: string | number;
}): Promise<void> {
  const { logger, projectRoot, projectDir, token } = opts;
  const port = opts.backendPort ?? process.env.PORT ?? 6060;
  const url = `http://127.0.0.1:${port}/api/opencode/hooks/${encodeURIComponent(projectDir)}`;

  const content = `// AUTO-GENERATED by etienne (OpenCode hook bridge). Do not edit — regenerated per run.
const CFG = { url: ${JSON.stringify(url)}, token: ${JSON.stringify(token)} };

async function post(kind, payload) {
  try {
    await fetch(CFG.url, {
      method: "POST",
      headers: { "content-type": "application/json", "x-etienne-hook-token": CFG.token },
      body: JSON.stringify({ kind, ...payload }),
      signal: AbortSignal.timeout(1500),
    });
  } catch {} // never break the agent on telemetry failure
}

export const EtienneHooks = async ({ directory }) => {
  post("plugin_init", { directory });
  return {
    "tool.execute.before": async (input, output) =>
      post("pre_tool_use", {
        tool: input.tool,
        sessionID: input.sessionID,
        callID: input.callID,
        args: output.args,
      }),
    "tool.execute.after": async (input, output) =>
      post("post_tool_use", {
        tool: input.tool,
        sessionID: input.sessionID,
        callID: input.callID,
        args: input.args,
        title: output.title,
        output: typeof output.output === "string" ? output.output.slice(0, 4000) : output.output,
        metadata: output.metadata,
      }),
  };
};
`;

  const pluginDir = path.join(projectRoot, '.opencode', 'plugin');
  const pluginPath = path.join(pluginDir, 'etienne-hooks.js');

  try {
    const existing = await fs.readFile(pluginPath, 'utf-8').catch(() => undefined);
    if (existing === content) return;

    await fs.ensureDir(pluginDir);
    await fs.writeFile(pluginPath, content, 'utf-8');
    logger.debug(`Provisioned OpenCode hook plugin at ${pluginPath}`);
  } catch (err: any) {
    logger.warn(`Failed to provision OpenCode hook plugin: ${err?.message}`);
  }
}
